### ISSUE TITLE
test examples/ on mobile 

### ISSUE THREAD

**Issue by montoyamoraga** [processing/p5.sound.js-ARCHIVE#31]
please let me know if the [examples](https://processing.github.io/p5.sound.js/examples/) work on your phone or tablet, please include this info:

- device maker (Apple, Google, Samsung, etc)
- device model (iPhone 8, Galaxy Samsung, etc)
- operating system (Apple iOs, Android, etc)
- web browser and version (Chrome, Firefox, Safari, etc)

note: these are the browsers we are currently supporting: https://browserslist.dev/?q=bGFzdCAyIHZlcnNpb25zLCBub3QgZGVhZA%3D%3D

**Comment by gerceboss** [comment]
@montoyamoraga 
Hello sir ,this is my first contribution to this organization.
I have checked and tested on my phone: OnePlus NORD CE (Android )
 I  have  verified this on Chrome
In these examples, 
delay ,amplitude modulation and mic-input do not work, and the ones mentioned below "other examples" also donot work properly.
And I have observed a bug ,that on clicking anywhere  in the rectangular box the color changes as well as they are not responsive .

**Comment by littlejacinthe** [comment]
Hello @montoyamoraga 
I had a look at the examples 
- device maker : Samsung
- device model : Galaxy A32 4G
- operating system : Android
- web browser : Chrome version 119.0.6045.163 & Opera version 78.5.4143.75924
(the following remarks were observed on both web browsers, on the same device)

All the 'new' examples link to a page that only has a Start Audio and Stop Audio button. None of those buttons work. 
For the 'original' examples, they all work except : 
- Delay : the link brings me back to the examples page

Sometimes the visualizer is not perfectly in sync with the sound. 
All examples work better after hitting the 'reset' button, otherwise they can be a bit slow. 
For modulations and filters it's hard to interact with on mobile as you have to scroll on your screen to modulate, which is a bit impractical.

**Comment by montoyamoraga** [comment]
hi!
sorry that was my mistake, i moved the examples from github pages,
to the p5.js editor on this collection
https://editor.p5js.org/montoyamoraga/collections/xydp5uPw0
i hope this makes it easier to test!
thanks so much for your help!

**Comment by montoyamoraga** [comment]
closing for now
